/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface T {
  'id' : bigint,
  'ownerName' : string,
  'phone' : string,
  'truckNumber' : string,
}
export interface T__1 {
  'id' : bigint,
  'truckId' : bigint,
  'clientId' : bigint,
  'loadingQty' : number,
  'challanNo' : string,
  'doNo' : string,
  'createdBy' : string,
  'tripId' : string,
  'tpNo' : string,
  'unloadingQty' : number,
  'loadingDate' : string,
  'associateType' : string,
  'shortage' : number,
  'consignee' : string,
  'consigner' : string,
}
export interface T__2 {
  'id' : bigint,
  'pan' : string,
  'status' : string,
  'tripCost' : number,
  'tripId' : bigint,
  'tdsPercent' : number,
  'tdsAmount' : number,
}
export interface T__3 {
  'id' : bigint,
  'remark' : string,
  'truckId' : bigint,
  'expenseType' : string,
  'date' : string,
  'amount' : number,
}
export interface T__4 {
  'id' : bigint,
  'paymentStatus' : string,
  'balance' : number,
  'bankDetails' : string,
  'tripId' : bigint,
  'totalCost' : number,
  'paidAmount' : number,
}
export interface T__5 {
  'id' : bigint,
  'billingAmount' : number,
  'status' : string,
  'tripId' : bigint,
  'rate' : number,
  'gstPercent' : number,
  'gstAmount' : number,
  'totalInvoice' : number,
}
export interface T__6 {
  'id' : bigint,
  'truckId' : bigint,
  'total' : number,
  'date' : string,
  'rate' : number,
  'litre' : number,
  'vendor' : string,
}
export interface T__7 {
  'id' : bigint,
  'clientName' : string,
  'gstNumber' : string,
  'address' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[string, string, string], bigint>,
  'createDieselEntry' : ActorMethod<
    [bigint, string, string, number, number, number],
    bigint
  >,
  'createInvoice' : ActorMethod<
    [bigint, number, number, number, number, number, string],
    bigint
  >,
  'createPayment' : ActorMethod<
    [bigint, number, number, number, string, string],
    bigint
  >,
  'createPettyCash' : ActorMethod<
    [bigint, string, string, number, string],
    bigint
  >,
  'createTDSEntry' : ActorMethod<
    [bigint, number, number, number, string, string],
    bigint
  >,
  'createTrip' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
    ],
    bigint
  >,
  'createTruck' : ActorMethod<[string, string, string], bigint>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteData' : ActorMethod<[string], undefined>,
  'deleteDieselEntry' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'deletePettyCash' : ActorMethod<[bigint], undefined>,
  'deleteTDSEntry' : ActorMethod<[bigint], undefined>,
  'deleteTrip' : ActorMethod<[bigint], undefined>,
  'deleteTruck' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<T__7>>,
  'getAllDieselEntries' : ActorMethod<[], Array<T__6>>,
  'getAllInvoices' : ActorMethod<[], Array<T__5>>,
  'getAllKeys' : ActorMethod<[], Array<string>>,
  'getAllPayments' : ActorMethod<[], Array<T__4>>,
  'getAllPettyCashEntries' : ActorMethod<[], Array<T__3>>,
  'getAllTDSEntries' : ActorMethod<[], Array<T__2>>,
  'getAllTrips' : ActorMethod<[], Array<T__1>>,
  'getAllTrucks' : ActorMethod<[], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], T__7>,
  'getData' : ActorMethod<[string], [] | [string]>,
  'getDieselEntry' : ActorMethod<[bigint], T__6>,
  'getInvoice' : ActorMethod<[bigint], T__5>,
  'getPayment' : ActorMethod<[bigint], T__4>,
  'getPettyCash' : ActorMethod<[bigint], T__3>,
  'getTDSEntry' : ActorMethod<[bigint], T__2>,
  'getTrip' : ActorMethod<[bigint], T__1>,
  'getTruck' : ActorMethod<[bigint], T>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setData' : ActorMethod<[string, string], undefined>,
  'updateClient' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateDieselEntry' : ActorMethod<
    [bigint, bigint, string, string, number, number, number],
    undefined
  >,
  'updateInvoice' : ActorMethod<
    [bigint, bigint, number, number, number, number, number, string],
    undefined
  >,
  'updatePayment' : ActorMethod<
    [bigint, bigint, number, number, number, string, string],
    undefined
  >,
  'updatePettyCash' : ActorMethod<
    [bigint, bigint, string, string, number, string],
    undefined
  >,
  'updateTDSEntry' : ActorMethod<
    [bigint, bigint, number, number, number, string, string],
    undefined
  >,
  'updateTrip' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
    ],
    undefined
  >,
  'updateTruck' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];