/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface T__3 {
    id: bigint;
    remark: string;
    truckId: bigint;
    expenseType: string;
    date: string;
    amount: number;
}
export interface T__2 {
    id: bigint;
    pan: string;
    status: string;
    tripCost: number;
    tripId: bigint;
    tdsPercent: number;
    tdsAmount: number;
}
export interface T {
    id: bigint;
    ownerName: string;
    phone: string;
    truckNumber: string;
}
export interface T__7 {
    id: bigint;
    clientName: string;
    gstNumber: string;
    address: string;
}
export interface T__5 {
    id: bigint;
    billingAmount: number;
    status: string;
    tripId: bigint;
    rate: number;
    gstPercent: number;
    gstAmount: number;
    totalInvoice: number;
}
export interface T__1 {
    id: bigint;
    truckId: bigint;
    clientId: bigint;
    loadingQty: number;
    challanNo: string;
    doNo: string;
    createdBy: string;
    tripId: string;
    tpNo: string;
    unloadingQty: number;
    loadingDate: string;
    associateType: string;
    shortage: number;
    consignee: string;
    consigner: string;
}
export interface T__6 {
    id: bigint;
    truckId: bigint;
    total: number;
    date: string;
    rate: number;
    litre: number;
    vendor: string;
}
export interface UserProfile {
    name: string;
}
export interface T__4 {
    id: bigint;
    paymentStatus: string;
    balance: number;
    bankDetails: string;
    tripId: bigint;
    totalCost: number;
    paidAmount: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClient(clientName: string, gstNumber: string, address: string): Promise<bigint>;
    createDieselEntry(truckId: bigint, date: string, vendor: string, litre: number, rate: number, total: number): Promise<bigint>;
    createInvoice(tripId: bigint, rate: number, billingAmount: number, gstPercent: number, gstAmount: number, totalInvoice: number, status: string): Promise<bigint>;
    createPayment(tripId: bigint, totalCost: number, paidAmount: number, balance: number, bankDetails: string, paymentStatus: string): Promise<bigint>;
    createPettyCash(truckId: bigint, date: string, expenseType: string, amount: number, remark: string): Promise<bigint>;
    createTDSEntry(tripId: bigint, tripCost: number, tdsPercent: number, tdsAmount: number, pan: string, status: string): Promise<bigint>;
    createTrip(challanNo: string, truckId: bigint, clientId: bigint, tpNo: string, doNo: string, consigner: string, consignee: string, loadingDate: string, loadingQty: number, unloadingQty: number, associateType: string, createdBy: string): Promise<bigint>;
    createTruck(truckNumber: string, ownerName: string, phone: string): Promise<bigint>;
    deleteClient(id: bigint): Promise<void>;
    deleteData(key: string): Promise<void>;
    deleteDieselEntry(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deletePayment(id: bigint): Promise<void>;
    deletePettyCash(id: bigint): Promise<void>;
    deleteTDSEntry(id: bigint): Promise<void>;
    deleteTrip(id: bigint): Promise<void>;
    deleteTruck(id: bigint): Promise<void>;
    getAllClients(): Promise<Array<T__7>>;
    getAllDieselEntries(): Promise<Array<T__6>>;
    getAllInvoices(): Promise<Array<T__5>>;
    getAllKeys(): Promise<Array<string>>;
    getAllPayments(): Promise<Array<T__4>>;
    getAllPettyCashEntries(): Promise<Array<T__3>>;
    getAllTDSEntries(): Promise<Array<T__2>>;
    getAllTrips(): Promise<Array<T__1>>;
    getAllTrucks(): Promise<Array<T>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(id: bigint): Promise<T__7>;
    getData(key: string): Promise<string | null>;
    getDieselEntry(id: bigint): Promise<T__6>;
    getInvoice(id: bigint): Promise<T__5>;
    getPayment(id: bigint): Promise<T__4>;
    getPettyCash(id: bigint): Promise<T__3>;
    getTDSEntry(id: bigint): Promise<T__2>;
    getTrip(id: bigint): Promise<T__1>;
    getTruck(id: bigint): Promise<T>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setData(key: string, value: string): Promise<void>;
    updateClient(id: bigint, clientName: string, gstNumber: string, address: string): Promise<void>;
    updateDieselEntry(id: bigint, truckId: bigint, date: string, vendor: string, litre: number, rate: number, total: number): Promise<void>;
    updateInvoice(id: bigint, tripId: bigint, rate: number, billingAmount: number, gstPercent: number, gstAmount: number, totalInvoice: number, status: string): Promise<void>;
    updatePayment(id: bigint, tripId: bigint, totalCost: number, paidAmount: number, balance: number, bankDetails: string, paymentStatus: string): Promise<void>;
    updatePettyCash(id: bigint, truckId: bigint, date: string, expenseType: string, amount: number, remark: string): Promise<void>;
    updateTDSEntry(id: bigint, tripId: bigint, tripCost: number, tdsPercent: number, tdsAmount: number, pan: string, status: string): Promise<void>;
    updateTrip(id: bigint, challanNo: string, truckId: bigint, clientId: bigint, tpNo: string, doNo: string, consigner: string, consignee: string, loadingDate: string, loadingQty: number, unloadingQty: number, associateType: string, createdBy: string): Promise<void>;
    updateTruck(id: bigint, truckNumber: string, ownerName: string, phone: string): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2);
            return result;
        }
    }
    async createDieselEntry(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDieselEntry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDieselEntry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createInvoice(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createPayment(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createPettyCash(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPettyCash(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPettyCash(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTDSEntry(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTDSEntry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTDSEntry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createTrip(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: number, arg9: number, arg10: string, arg11: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async createTruck(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTruck(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTruck(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteData(arg0);
            return result;
        }
    }
    async deleteDieselEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDieselEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDieselEntry(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deletePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deletePettyCash(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePettyCash(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePettyCash(arg0);
            return result;
        }
    }
    async deleteTDSEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTDSEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTDSEntry(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async deleteTruck(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTruck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTruck(arg0);
            return result;
        }
    }
    async getAllClients(): Promise<Array<T__7>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllDieselEntries(): Promise<Array<T__6>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDieselEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDieselEntries();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<T__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKeys();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<T__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return result;
        }
    }
    async getAllPettyCashEntries(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPettyCashEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPettyCashEntries();
            return result;
        }
    }
    async getAllTDSEntries(): Promise<Array<T__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTDSEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTDSEntries();
            return result;
        }
    }
    async getAllTrips(): Promise<Array<T__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return result;
        }
    }
    async getAllTrucks(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrucks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrucks();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: bigint): Promise<T__7> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return result;
        }
    }
    async getData(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getData(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getData(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDieselEntry(arg0: bigint): Promise<T__6> {
        if (this.processError) {
            try {
                const result = await this.actor.getDieselEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDieselEntry(arg0);
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<T__5> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return result;
        }
    }
    async getPayment(arg0: bigint): Promise<T__4> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return result;
        }
    }
    async getPettyCash(arg0: bigint): Promise<T__3> {
        if (this.processError) {
            try {
                const result = await this.actor.getPettyCash(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPettyCash(arg0);
            return result;
        }
    }
    async getTDSEntry(arg0: bigint): Promise<T__2> {
        if (this.processError) {
            try {
                const result = await this.actor.getTDSEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTDSEntry(arg0);
            return result;
        }
    }
    async getTrip(arg0: bigint): Promise<T__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return result;
        }
    }
    async getTruck(arg0: bigint): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.getTruck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTruck(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setData(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setData(arg0, arg1);
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateDieselEntry(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDieselEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDieselEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateInvoice(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updatePayment(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updatePettyCash(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: number, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePettyCash(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePettyCash(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTDSEntry(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTDSEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTDSEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateTrip(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: number, arg10: number, arg11: string, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async updateTruck(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTruck(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTruck(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
